(function(){
'use strict';
const C=window.KitchenCore,A=window.BakeryArt,$=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const speaker='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 9h4l5-4v14l-5-4H3zm12-1q5 4 0 8m3-11q8 7 0 14"/></svg>';
const good=['flour','butter','sugar','egg','milk','berry','chocolate','jam','lemon','cherry','blueberry','banana'];
const silly=['sock','car','boot','button','leaf','stone','pencil','duck'];
const ingredientNames={berry:'berry',car:'toy car',boot:'boot',button:'button',duck:'rubber duck',stone:'pebble',blueberry:'blueberries'};
const sharedMatch=(window.location?.hash||'').match(/^#menu=([a-f0-9]{64})$/),sharedId=sharedMatch?.[1],sharedRequested=/^#menu=/.test(window.location?.hash||'');
const key=sharedId?'monster-bakery-student-'+sharedId:'monster-bakery-v1';
let sharedTitle='',shareBusy=false,shareRequest=null;
let voice=null,playingAudio=null,bakeTimer=null,practice=null,draft=[],storageOK=true;
function newWord(text){const audio=window.BakeryRecordings?.[text]||null;return {text,cue:A[text]?'both':'audio',art:A[text]?text:null,image:null,audio};}
function preset(type){return (type==='food'?['cake','milk','egg','jam','fish','cup','sugar','butter']:['cat','sun','cup','dog','map','sock','duck','pig','hat','sea']).map(newWord);}

function newProgress(){return {stars:0,orders:0,active:null};}
let state={version:1,player:'Player 1',config:{count:5,words:preset('first'),voiceMode:'monster'},players:{'Player 1':newProgress()}};
function validWord(w){return w&&typeof w.text==='string'&&w.text.length<=40&&/^[a-z][a-z '\-]*$/i.test(w.text)&&['audio','picture','both'].includes(w.cue)&&(!w.image||/^data:image\/(png|jpeg|webp);base64,/.test(w.image))&&(!w.audio||/^data:audio\/[\w.+-]+;base64,/.test(w.audio));}
function validOrder(o){return !o||(Array.isArray(o.words)&&o.words.length>0&&o.words.length<=12&&o.words.every(validWord)&&Array.isArray(o.answers)&&o.answers.length<=o.words.length&&o.answers.every(a=>typeof a.typed==='string'&&typeof a.correct==='boolean')&&['spell','feedback','ready','baking','serve','result'].includes(o.stage)&&typeof o.awarded==='boolean'&&((['ready','baking','serve','result'].includes(o.stage))?o.answers.length===o.words.length:true));}
try{const raw=localStorage.getItem(key);if(raw){const s=JSON.parse(raw);if(s.version===1&&typeof s.player==='string'&&s.config&&Array.isArray(s.config.words)&&s.config.words.length&&s.config.words.every(validWord)&&s.players&&Object.values(s.players).every(p=>Number.isFinite(p.stars)&&p.stars>=0&&Number.isInteger(p.orders)&&p.orders>=0&&validOrder(p.active))&&Object.hasOwn(s.players,s.player)){state=s;state.config.voiceMode=['standard','recordings','monster'].includes(state.config.voiceMode)?state.config.voiceMode:'monster';state.config.count=Math.max(1,Math.min(12,Number(state.config.count)||5));}}}catch(e){storageOK=false;}
function syncRecordings(){
const recordings=new Map(Object.entries(window.BakeryRecordings||{}));
for(const w of state.config.words)if(w.audio)recordings.set(C.normalize(w.text),w.audio);
for(const words of [state.config.words,...Object.values(state.players).map(p=>p.active?.words||[])])for(const w of words)if(!w.audio)w.audio=recordings.get(C.normalize(w.text))||null;
}
syncRecordings();
function progress(){return state.players[state.player];}
function save(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;}$('saveWarning').hidden=storageOK;$('saveStatus').textContent=storageOK?'Your bakery grows on this device.':'This session only. Progress is not saved.';return storageOK;}
function stopAudio(){window.dispatchEvent(new CustomEvent('bakery-quiet'));if(playingAudio){playingAudio.pause();playingAudio=null;}if(window.speechSynthesis)window.speechSynthesis.cancel();}
function findVoice(){voice=window.speechSynthesis?.getVoices().find(v=>v.name==='Google UK English Female')||null;}
findVoice();window.speechSynthesis?.addEventListener('voiceschanged',()=>{findVoice();const b=$('hearWord');if(b){const o=progress().active;const w=practice?practice.words[practice.index]:o?.words[o.answers.length];if(w)wireAudio(w);}});
function canHear(w){return !!w.audio||(state.config.voiceMode==='standard'&&!!voice);}
function playWord(w,onError){window.dispatchEvent(new CustomEvent('bakery-word-play'));stopAudio();if(w.audio){playingAudio=new Audio(w.audio);playingAudio.play().catch(()=>onError?.('This recording could not play. Try again or ask your teacher to say the word.'));}else if(state.config.voiceMode==='standard'&&voice){const u=new SpeechSynthesisUtterance(w.text);u.voice=voice;u.lang='en-GB';u.rate=.9;u.onerror=()=>onError?.('Audio is unavailable. Ask your teacher to say the word.');window.speechSynthesis.speak(u);}}
function imageHTML(w){if(w.image)return '<img src="'+esc(w.image)+'" alt="Spelling picture">';return A[w.art]||'';}
function cueHTML(w){const showPic=w.cue!=='audio'&&!!(w.image||A[w.art]);const showAudio=w.cue!=='picture'||!!w.audio;return '<div class="cue '+(!showPic?'audio-only':'')+'">'+(showPic?'<div class="picture-cue" aria-label="Spelling picture">'+imageHTML(w)+'</div>':'')+(showAudio?'<button type="button" class="sound-button" id="hearWord">'+speaker+' Hear the word</button><p class="cue-note" id="audioNote"></p>':'')+'</div>';}
function wireAudio(w){const button=$('hearWord');if(!button)return;button.disabled=!canHear(w);const note=$('audioNote');note.textContent=canHear(w)?'Listen as many times as you like.':'Ask your teacher to say this word.';button.onclick=()=>playWord(w,msg=>{note.textContent=msg;});}
function playNextCue(w){const button=$('hearWord'),note=$('audioNote');if(!button||button.disabled||!w)return;playWord(w,msg=>{if(note&&note===$('audioNote'))note.textContent=msg;});}
function ingredients(o){const offset=(Number(o.variant)||0)*3;return o.answers.map((a,i)=>({art:(o.bonusStage||a.correct)?good[(i+offset)%good.length]:silly[(i+offset)%silly.length],correct:!!o.bonusStage||a.correct}));}
function cakeArt(o){const r=C.recipe(ingredients(o));if(!r.bad){const c=C.cakeStyle(o);return '<svg viewBox="0 0 200 160" role="img" aria-label="'+c.name+' cake"><ellipse cx="100" cy="140" rx="84" ry="12" fill="#e1d5bb"/><path d="M35 75h130v58q-65 18-130 0Z" fill="'+c.sponge+'"/><path d="M35 75v25q12 17 23 0 12 20 24 0 12 19 24 0 13 20 25 0 17 18 34 0V75Z" fill="'+c.icing+'"/><ellipse cx="100" cy="75" rx="65" ry="20" fill="'+c.icing+'"/>'+[58,85,115,140].map((x,i)=>'<circle cx="'+x+'" cy="'+(i%2?57:69)+'" r="9" fill="'+c.topping+'"/>').join('')+'</svg>';}const icons=r.surprises.slice(0,5).map((kind,i)=>'<g transform="translate('+(20+i*31)+' '+(i%2?35:20)+') scale(.28)">'+(A[kind]||'')+'</g>').join('');return '<svg class="mini-cake" viewBox="0 0 200 160" role="img" aria-label="Wonky cake with '+r.bad+' surprising ingredients"><ellipse cx="100" cy="140" rx="85" ry="13" fill="#e1d5bb"/><path d="M32 78Q96 53 167 84L160 131Q100 151 37 129Z" fill="#95744d"/><path d="M30 77Q96 54 167 79L163 105Q152 83 143 111Q130 86 118 103Q100 85 85 110Q68 89 57 102Q39 82 34 101Z" fill="'+r.icing+'"/><ellipse cx="97" cy="78" rx="67" ry="19" fill="'+r.icing+'"/>'+icons+'</svg>';}
function scene(){const p=progress(),o=p.active,n=o?o.words.length:Math.min(state.config.count,state.config.words.length);$('bank').textContent=p.stars;$('levelLabel').textContent=C.upgrades[C.level(p.stars)].name;$('ticketCount').textContent=n+(n===1?' word':' words');const next=C.upgrades.find(u=>u.at>p.stars),prev=C.upgrades[C.level(p.stars)];$('upgradeLabel').textContent=next?'Next: '+next.item.toLowerCase():'Your bakery has every upgrade!';$('upgradeCount').textContent=next?p.stars+' / '+next.at+' stars':p.stars+' stars earned';$('upgradeFill').style.width=next?Math.min(100,(p.stars-prev.at)/(next.at-prev.at)*100)+'%':'100%';
$('ingredientTray').innerHTML=o&&o.answers.length?ingredients(o).map(x=>'<div class="ingredient '+(x.correct?'':'bad')+'" title="'+esc(ingredientNames[x.art]||x.art)+'">'+A[x.art]+'<span>'+esc(ingredientNames[x.art]||x.art)+'</span></div>').join(''):'<span class="empty-tray">A little spelling. A little baking. A lot of cake.</span>';
$('orderTag').textContent=o?({spell:'MIXING TIME',feedback:'INTO THE BOWL',ready:'READY TO BAKE',baking:'IN THE OVEN',serve:'ORDER UP!',result:'CHEF’S REVIEW'}[o.bonusStage||o.stage]):'OPEN FOR CAKE';window.bakeryWorldState={stars:p.stars,stage:o?.bonusStage||o?.stage||'welcome',orderId:o?.id||'',count:o?.answers.length||0,total:n,correct:o?(o.bonusStage?n:C.score(o)):0,cakeStyle:o?C.cakeStyle(o):C.cakes[0],ingredients:o?ingredients(o):[]};window.dispatchEvent(new CustomEvent('bakery-state',{detail:window.bakeryWorldState}));}
function say(text,mood=''){$('monsterSpeech').textContent=text;window.dispatchEvent(new CustomEvent('bakery-mood',{detail:mood}));}
function header(o){return '<div class="panel-header"><span class="eyebrow">WORD '+Math.min(o.answers.length+(o.stage==='spell'?1:0),o.words.length)+' OF '+o.words.length+'</span><div class="progress-dots" aria-hidden="true">'+o.words.map((w,i)=>'<i class="'+(o.answers[i]?(o.answers[i].correct?'done':'wrong'):(i===o.answers.length?'current':''))+'"></i>').join('')+'</div></div>';}
function panel(html,kind){$('orderPanel').className='order-panel '+(kind||'');$('orderPanel').innerHTML=html;}
function focus(id){requestAnimationFrame(()=>$(id)?.focus({preventScroll:true}));}
function render(){scene();if(sharedTitle)$('ticketCount').textContent=sharedTitle;const o=progress().active;stopAudio();if(practice){renderPractice();return;}if(!o){welcome();return;}if(o.bonusStage){renderBonus(o);return;}if(o.stage==='spell'){const w=o.words[o.answers.length];say('What goes in next?');panel(header(o)+'<h2 class="prompt-heading">Spell a little magic.</h2>'+cueHTML(w)+'<form class="word-form" id="wordForm"><label for="spellingInput">Type the word</label><input id="spellingInput" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="60" aria-describedby="wordError"><p id="wordError" class="error" role="alert"></p><button class="primary wide" type="submit">Add to the bowl <span aria-hidden="true">↗</span></button></form>');wireAudio(w);$('wordForm').onsubmit=e=>{e.preventDefault();const input=$('spellingInput').value;if(!C.answer(o,input)){$('wordError').textContent='Type a word first.';return;}save();render();dropIngredient(ingredients(o)[o.answers.length-1].art);focus('nextWord');};focus('spellingInput');
}else if(o.stage==='feedback'){const i=o.answers.length-1,a=o.answers[i],w=o.words[i],x=ingredients(o)[i];say(a.correct?'Ooh, that belongs in a cake!':({'sock':'A sock? A very chewy choice!','car':'Vroom! That is a toy car.','boot':'A boot? My cake has shoes!','button':'A button? Fashionable cake!'}[x.art]||'An unexpected ingredient!'),a.correct?'happy':'surprised');panel(header(o)+'<div class="feedback-icon '+(a.correct?'':'bad')+'">'+A[x.art]+'</div><h2 class="feedback-heading">'+(a.correct?'Lovely spelling!':'A surprising ingredient!')+'</h2><p class="feedback-copy">'+(a.correct?'In goes the '+(ingredientNames[x.art]||x.art)+'.':'Have a look at this word. We can try it again after baking.')+'</p>'+(a.correct?'':'<p class="typed-answer">You wrote: '+esc(a.typed)+'</p>')+'<div class="spell-model">'+esc(w.text)+'</div><div class="next-button"><button id="nextWord" class="primary wide">'+(o.answers.length===o.words.length?'Ready for the oven':'Next word')+'</button></div>');$('nextWord').onclick=()=>{C.next(o);save();render();if(o.stage==='spell')playNextCue(o.words[o.answers.length]);};
}else if(o.stage==='ready'){say('Let’s see what we have baked!');panel('<p class="eyebrow">ALL '+o.words.length+' INGREDIENTS ARE IN</p><div class="ready-art">'+cakeArt(o)+'</div><h2 class="ready-title">Time to bake!</h2><p class="ready-copy">Your recipe is ready.<br>Let’s put it in the oven.</p><div class="next-button"><button class="primary wide" id="bake">Bake my cake</button></div>');$('bake').onclick=()=>{o.stage='baking';save();render();};
}else if(o.stage==='baking'){say(C.score(o)===o.words.length?'Here comes the cake magic!':'This recipe has a few surprises…');panel('<p class="eyebrow">THE OVEN IS ON</p><div class="baking-spinner" aria-hidden="true"></div><h2 class="ready-title">A pinch of patience.</h2><p class="ready-copy" role="status">Mixing, bubbling, rising…</p><div class="bake-steps" aria-hidden="true"><span>Mix</span><span>Bake</span><span>Ta-da!</span></div>');clearTimeout(bakeTimer);bakeTimer=setTimeout(()=>{if(progress().active===o&&o.stage==='baking'){o.stage='serve';save();render();}},5600);
}else if(o.stage==='serve'){say('Is that for me?');panel('<p class="eyebrow">FRESH FROM THE OVEN</p><div class="ready-art">'+cakeArt(o)+'</div><h2 class="ready-title">One cake. One hungry monster.</h2><p class="ready-copy">Your customer is ready for a taste!</p><div class="next-button"><button class="primary wide" id="serve">Serve the cake</button></div>');$('serve').onclick=()=>{const reward=C.award(o,progress());o.unlocked=reward.unlocked.map(x=>x.item);save();render();};
}else{result(o);}}
function dropIngredient(art){window.dispatchEvent(new CustomEvent('bakery-drop',{detail:art}));const b=$('nextWord');if(b){b.disabled=true;setTimeout(()=>{if(b===$('nextWord'))b.disabled=false;},1650);}}
function welcome(){say('Did somebody say cake?');panel('<p class="eyebrow">YOUR TABLE IS READY</p><h1>A recipe for<br><em>little adventures.</em></h1><p class="intro-copy">Mochi is waiting for his cake. Spell the words, mix your ingredients and turn this little bakery into something wonderful.</p><div class="welcome-bottom"><div class="steps"><div><span class="step-art letters">abc</span><b>Spell</b>Find the word</div><div><span class="step-art">'+A.butter+'</span><b>Mix</b>Fill your bowl</div><div><span class="step-art">'+A.cake+'</span><b>Serve</b>Earn your stars</div></div><button class="primary wide" id="start">Let’s bake <span aria-hidden="true">→</span></button><p class="subtle">'+Math.min(state.config.count,state.config.words.length)+' words per cake · '+esc(state.player)+'’s bakery</p></div>','welcome');const d=sharedRequested?null:readDraft();if(d&&(d.text.split(/\n/).map(C.normalize).filter(Boolean).join('\n')!==state.config.words.map(w=>w.text).join('\n')||Number(d.count)!==state.config.count)){$('start').textContent='Finish setting up your words';$('start').onclick=()=>$('settingsButton').onclick();$('saveStatus').textContent='Your new word list is saved as a draft. Finish setup to use it.';}else $('start').onclick=startOrder;}
function startOrder(){practice=null;progress().active=C.makeOrder(state.config.words,state.config.count);progress().active.variant=progress().orders%C.cakes.length;save();render();}
function result(o){const s=C.score(o),n=o.words.length,miss=o.words.filter((w,i)=>!o.answers[i].correct);say(s===n?'Every ingredient was delicious!':s===0?'An adventurous recipe. Let’s practise together!':'Some lovely flavours. And a surprise or two!',s===n?'happy':'');panel('<p class="eyebrow">THE MONSTER’S REVIEW</p><div class="result-rating"><strong>'+s+' / '+n+'</strong><div class="result-stars" aria-label="'+s+' out of '+n+' stars">'+'★'.repeat(s)+'<span class="empty">'+'☆'.repeat(n-s)+'</span></div><p>'+s+(s===1?' star':' stars')+' added to your bakery</p></div><h2 class="result-title">'+(s===n?'A delicious success!':s===0?'A cake full of surprises.':'Baked with a little surprise.')+'</h2><p class="feedback-copy">'+(s===n?'Every ingredient was just right.':miss.length===1?'One word to practise for your next recipe.':miss.length+' words to practise for your next recipe.')+'</p>'+((o.unlocked||[]).length?'<div class="reward-box">New for your bakery: '+o.unlocked.map(esc).join(', ')+'.</div>':'<p class="order-summary">'+progress().orders+(progress().orders===1?' cake served':' cakes served')+' · '+progress().stars+(progress().stars===1?' star earned</p>':' stars earned</p>'))+'<div class="result-actions">'+(miss.length?'<button class="secondary wide" id="practise">Practise '+miss.length+(miss.length===1?' word':' words')+'</button>':'')+'<button class="primary wide" id="another">Bake another cake</button></div>');if($('practise'))$('practise').onclick=()=>{practice={words:miss,index:0,stage:'look'};render();};$('another').onclick=startOrder;}
function renderPractice(){stopAudio();const w=practice.words[practice.index];say('Let’s get this one ready for next time.');const top='<p class="eyebrow">PRACTICE '+(practice.index+1)+' OF '+practice.words.length+' · NO EXTRA STARS</p>';
if(practice.stage==='look'){panel(top+'<h2 class="prompt-heading">Look. Say. Remember.</h2>'+cueHTML(w)+'<div class="spell-model">'+esc(w.text)+'</div><p class="feedback-copy">Say the sounds, then look at the spelling.</p><div class="next-button"><button class="primary wide" id="hideWord">Hide it and try</button></div>');wireAudio(w);$('hideWord').onclick=()=>{practice.stage='try';renderPractice();focus('practiceInput');};
}else if(practice.stage==='try'){panel(top+'<h2 class="prompt-heading">Your turn.</h2>'+cueHTML(w)+'<form class="word-form" id="practiceForm"><label for="practiceInput">Spell the word</label><input id="practiceInput" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="60"><p id="practiceError" class="error" role="alert"></p><button class="primary wide">Check my spelling</button></form>');wireAudio(w);$('practiceForm').onsubmit=e=>{e.preventDefault();const typed=$('practiceInput').value;if(!C.normalize(typed)){$('practiceError').textContent='Type a word first.';return;}practice.stage=C.normalize(typed)===C.normalize(w.text)?'done':'look';renderPractice();};
}else{panel(top+'<div class="feedback-icon">'+A.berry+'</div><h2 class="feedback-heading">You’ve got it!</h2><div class="spell-model">'+esc(w.text)+'</div><p class="feedback-copy">That word is ready for another recipe.</p><div class="next-button"><button class="primary wide" id="practiceNext">'+(practice.index+1===practice.words.length?'Bake my reward cake':'Next practice word')+'</button></div>');$('practiceNext').onclick=()=>{practice.index++;if(practice.index>=practice.words.length){C.finishPractice(progress().active,practice.words.map(w=>w.text));practice=null;save();render();}else{practice.stage='look';renderPractice();playNextCue(practice.words[practice.index]);}};}}
function renderBonus(o){const name=C.cakeStyle(o).name;if(o.bonusStage==='baking'){say('You fixed every word! This cake is for you.','happy');panel('<p class="eyebrow">PRACTICE REWARD</p><div class="baking-spinner" aria-hidden="true"></div><h2 class="ready-title">A well-earned cake!</h2><p class="ready-copy">Every practice word is correct. Your '+name.toLowerCase()+' cake is baking.</p>');clearTimeout(bakeTimer);bakeTimer=setTimeout(()=>{if(progress().active===o&&o.bonusStage==='baking'){o.bonusStage='serve';save();render();}},5600);}else if(o.bonusStage==='serve'){say('A perfect recipe. You did it!','happy');panel('<p class="eyebrow">YOUR REWARD CAKE</p><div class="ready-art">'+cakeArt(o)+'</div><h2 class="ready-title">'+name+'</h2><p class="ready-copy">You kept trying until every word was right.</p><button class="primary wide" id="serveBonus">Share it with Mochi</button>');$('serveBonus').onclick=()=>{C.serveBonus(o,progress());save();render();};}else{say('Yummy! Practice tastes delicious.','happy');panel('<p class="eyebrow">PRACTICE COMPLETE</p><div class="ready-art">'+cakeArt(o)+'</div><h2 class="ready-title">Another cake to celebrate!</h2><p class="ready-copy">All your tricky words are ready for next time.</p><button class="primary wide" id="another">Bake another cake</button>');$('another').onclick=startOrder;}}
const draftKey='monster-bakery-menu-draft-v1';
function rememberDraft(){try{localStorage.setItem(draftKey,JSON.stringify({version:1,text:$('wordList').value,words:draft,name:$('playerName').value,count:$('roundSize').value,mode:$('voiceMode').value,title:$('menuTitle').value}));}catch(_){$('setupError').textContent='This browser could not save your draft. Keep this window open until you save the menu.';}}
function readDraft(){try{const d=JSON.parse(localStorage.getItem(draftKey)||'null');return d&&d.version===1&&typeof d.text==='string'&&d.text.length<=3000&&Array.isArray(d.words)&&d.words.length<=50&&d.words.every(validWord)&&typeof d.name==='string'&&['monster','recordings','standard'].includes(d.mode)?d:null;}catch(_){return null;}}
function clearDraft(){try{localStorage.removeItem(draftKey);}catch(_){}}
function menuChanged(words,count){return count!==state.config.count||JSON.stringify(words.map(w=>C.normalize(w.text)))!==JSON.stringify(state.config.words.map(w=>C.normalize(w.text)));}
function syncDraft(){const words=$('wordList').value.split(/\n/).map(C.normalize).filter(Boolean);if(!words.length||words.length>50)throw Error('Add between 1 and 50 words.');if(words.some(w=>w.length>40||!(/^[a-z][a-z '\-]*$/i.test(w))))throw Error('Use English words up to 40 characters. Apostrophes and hyphens are fine.');const unique=[...new Set(words)];draft=unique.map(text=>draft.find(w=>w.text===text)||newWord(text));$('wordList').value=unique.join('\n');}
function showDraft(){rememberDraft();const host=$('wordCards');host.replaceChildren();draft.forEach((w,i)=>{const row=document.createElement('div');row.className='word-card'+(!(w.image||A[w.art])?' no-picture':'');row.innerHTML=((w.image||A[w.art])?'<div class="thumb">'+imageHTML(w)+'</div>':'')+'<div><b>'+esc(w.text)+'</b><div class="word-options"><select aria-label="Cue for '+esc(w.text)+'"><option value="picture">Picture</option><option value="audio">Audio</option><option value="both">Picture + audio</option></select><label class="upload-label">Add picture<input type="file" accept="image/png,image/jpeg,image/webp" aria-label="Picture for '+esc(w.text)+'"></label><label class="upload-label">Add recording<input type="file" accept="audio/mpeg,audio/mp4,audio/wav,audio/x-wav,audio/ogg" aria-label="Recording for '+esc(w.text)+'"></label>'+(!w.audio&&w.cue!=='picture'&&$('voiceMode').value==='monster'?'<button type="button" class="record-word">Create Mochi voice</button>':'')+(w.audio?'<button type="button" class="preview">Play</button><button type="button" class="remove-audio">Remove audio</button>':'')+'</div><p class="audio-state">'+(w.audio?'Recording attached.':w.cue!=='picture'?($('voiceMode').value==='monster'?'Not recorded yet. Press Create Mochi voice.':$('voiceMode').value==='standard'?'Uses the standard voice on this device.':'Add a recording before saving.'):'Picture clue ready.')+'</p></div>';
row.querySelector('select').value=w.cue;row.querySelector('select').onchange=e=>{w.cue=e.target.value;showDraft();};const inputs=row.querySelectorAll('input');inputs[0].onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){$('setupError').textContent='Choose a PNG, JPG or WebP picture.';return;}try{w.image=await readFile(file,600*1024);w.cue=w.cue==='audio'?'both':w.cue;showDraft();$('setupError').textContent='';}catch(err){$('setupError').textContent=err.message;}};inputs[1].onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!/^audio\//.test(file.type)){$('setupError').textContent='Choose an MP3, M4A, WAV or OGG recording.';return;}try{w.audio=await readFile(file,250*1024);w.cue=w.cue==='picture'?'both':w.cue;showDraft();$('setupError').textContent='';}catch(err){$('setupError').textContent=err.message;}};if(row.querySelector('.record-word'))row.querySelector('.record-word').onclick=()=>generateRecordings([w]);if(w.audio){row.querySelector('.preview').onclick=()=>playWord(w,msg=>{$('setupError').textContent=msg;});row.querySelector('.remove-audio').onclick=()=>{w.audio=null;showDraft();};}host.append(row);});updateVoiceSummary();}
function readFile(file,max){if(file.size>max)return Promise.reject(Error('This file is too large. Use a file under '+Math.round(max/1024)+' KB.'));return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('This file could not be read.'));r.readAsDataURL(file);});}
function loadVoiceConnection(){const session=window.BakeryTeacher?.read();if(session){$('voiceToken').value=session.token;connectionStatus();return;}try{const remembered=localStorage.getItem('bakery-voice-teacher-code')||'';$('voiceToken').value=remembered||sessionStorage.getItem('bakery-voice-token')||'';$('rememberVoiceConnection').checked=!!remembered;}catch(_){}connectionStatus();}
function connectionStatus(){const session=window.BakeryTeacher?.read(),has=$('voiceToken').value.trim().length>=24;$('connectionStatus').textContent=session?'Signed in as the teacher. Create recordings for any words below.':has?'Voice connection ready. You can create recordings below.':'Starter recordings are ready. Sign in to record your own words.';$('showVoiceConnection').textContent='Advanced connection';$('teacherSignIn').hidden=!!session;$('teacherSignOut').hidden=!session;}
$('teacherSignIn').onclick=async()=>{const b=$('teacherSignIn');b.disabled=true;try{const session=await window.BakeryTeacher.signIn((msg,url)=>{const host=$('teacherSignInStatus');host.textContent=msg;if(url){const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.className='secondary';link.textContent='Continue with Google';host.append(document.createElement('br'),link);}});$('voiceToken').value=session.token;connectionStatus();$('teacherSignInStatus').textContent='Connected. You can now create Mochi recordings.';$('setupError').textContent='';}catch(e){$('teacherSignInStatus').textContent=e.message;}finally{b.disabled=false;}};
$('teacherSignOut').onclick=()=>{window.BakeryTeacher.forget();$('voiceToken').value='';try{localStorage.removeItem('bakery-voice-teacher-code');sessionStorage.removeItem('bakery-voice-token');}catch(_){}connectionStatus();$('teacherSignInStatus').textContent='Signed out. Saved recordings still play.';};
function storeVoiceConnection(){const token=$('voiceToken').value.trim();if(token.startsWith('session_')){connectionStatus();return;}if(token.length<24||token.length>200)throw Error('Enter the teacher connection code from your private voice settings.');try{sessionStorage.setItem('bakery-voice-token',token);if($('rememberVoiceConnection').checked)localStorage.setItem('bakery-voice-teacher-code',token);else localStorage.removeItem('bakery-voice-teacher-code');}catch(_){throw Error('This browser cannot remember the connection. Enable browser storage and try again.');}connectionStatus();}
$('connectVoice').onclick=()=>{try{storeVoiceConnection();$('setupError').textContent='';$('voiceConnection').open=false;}catch(e){$('setupError').textContent=e.message;}};
$('forgetVoice').onclick=()=>{try{localStorage.removeItem('bakery-voice-teacher-code');sessionStorage.removeItem('bakery-voice-token');}catch(_){}$('voiceToken').value='';$('rememberVoiceConnection').checked=false;connectionStatus();};
$('settingsButton').onclick=()=>{stopAudio();const pendingDraft=readDraft();draft=JSON.parse(JSON.stringify(pendingDraft?.words||state.config.words));$('wordList').value=pendingDraft?pendingDraft.text:draft.map(w=>w.text).join('\n');$('roundSize').value=pendingDraft?.count||state.config.count;$('playerName').value=pendingDraft?.name||state.player;$('voiceMode').value=pendingDraft?.mode||state.config.voiceMode;$('menuTitle').value=pendingDraft?.title||'Spelling practice';$('shareResult').hidden=true;renderSharedMenus();$('voiceProgress').textContent=pendingDraft?'Your unfinished menu has been restored. Save & use these words when ready.':'';loadVoiceConnection();$('setupError').textContent='';showDraft();$('setup').showModal();};
$('setupForm').addEventListener('input',e=>{if(['wordList','roundSize','playerName','menuTitle'].includes(e.target.id))rememberDraft();});
$('closeSetup').onclick=()=>{if(preparing||shareBusy)return;rememberDraft();stopAudio();$('setup').close();};$('setup').addEventListener('close',()=>{stopAudio();if(!progress().active)render();});
$('exportWords').onclick=()=>{try{syncDraft();const blob=new Blob([JSON.stringify({version:1,words:draft},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='monster-bakery-words.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(err){$('setupError').textContent=err.message;}};
$('applyWords').onclick=()=>{try{syncDraft();showDraft();$('setupError').textContent='';}catch(e){$('setupError').textContent=e.message;}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{draft=preset(b.dataset.preset);$('wordList').value=draft.map(w=>w.text).join('\n');showDraft();});
$('voiceMode').onchange=showDraft;
let preparing=false;
function updateVoiceSummary(){const missing=draft.filter(w=>w.cue!=='picture'&&!w.audio),mochi=$('voiceMode').value==='monster';$('generateVoices').hidden=!mochi;$('generateVoices').disabled=preparing||!missing.length;$('generateVoices').textContent=missing.length?'Create Mochi recordings ('+missing.length+')':'Mochi recordings ready';$('voiceSummary').textContent=missing.length?missing.length+' audio '+(missing.length===1?'word needs':'words need')+' a recording. No sound will play while recording.':'All audio clues are ready. Save your menu to use them in the game.';$('saveMenu').textContent=mochi&&missing.length?'Record & use these words':'Save & use these words';}
function revealVoiceConnection(){$('voiceConnection').open=true;$('voiceConnection').scrollIntoView?.({behavior:'smooth',block:'center'});$('voiceToken').focus();}
$('showVoiceConnection').onclick=revealVoiceConnection;
async function prepareWords(words){
const missing=words.filter(w=>w.cue!=='picture'&&!w.audio);if(!missing.length)return;
const token=$('voiceToken').value.trim();if(token.length<24){$('teacherSignIn').scrollIntoView?.({behavior:'smooth',block:'center'});$('teacherSignIn').focus();throw Error('Sign in with Google first, then press Create Mochi recordings.');}
storeVoiceConnection();preparing=true;stopAudio();$('setupError').textContent='';
const controls=[...$('setupForm').querySelectorAll('button,input,select,textarea')];controls.forEach(el=>el.disabled=true);
try{for(let i=0;i<missing.length;i++){$('voiceProgress').textContent='Recording '+(i+1)+' of '+missing.length+': '+missing[i].text+'…';const result=await window.BakeryVoice.prepare(missing[i].text,window.BakeryVoice.DEFAULT_ENDPOINT,token);missing[i].audio=result.audio;rememberDraft();}}
finally{preparing=false;controls.forEach(el=>el.disabled=false);showDraft();}
$('voiceProgress').textContent='Mochi recordings ready. Press Save menu to use them. Nothing has been played.';
}
function voiceFailure(err){if(/^Sign in as the teacher/.test(err.message)){window.BakeryTeacher?.forget();$('voiceToken').value='';connectionStatus();}$('setupError').textContent=err.message;}
async function generateRecordings(words){if(preparing)return;try{if(!words){syncDraft();showDraft();}await prepareWords(words||draft);}catch(err){$('voiceProgress').textContent='Any completed recordings are kept here. You can retry the remaining words.';voiceFailure(err);}}
$('generateVoices').onclick=()=>generateRecordings();
$('setupForm').onsubmit=async e=>{e.preventDefault();if(preparing||shareBusy)return;try{syncDraft();const name=$('playerName').value.trim()||'Player 1';if(['__proto__','constructor','prototype'].includes(name))throw Error('Choose a different bakery name.');const count=Number($('roundSize').value);if(!Number.isInteger(count)||count<1||count>12)throw Error('Choose between 1 and 12 words per cake.');if(draft.some(w=>w.cue!=='audio'&&!(w.image||A[w.art])))throw Error('Add a picture for every picture clue, or change its cue to audio.');const mode=$('voiceMode').value;
for(const w of draft)if(!w.audio&&window.BakeryRecordings?.[w.text])w.audio=window.BakeryRecordings[w.text];
if($('voiceToken').value.trim())storeVoiceConnection();
const missing=draft.filter(w=>w.cue!=='picture'&&!w.audio);
if(mode==='recordings'&&missing.length)throw Error('Add a recording for '+missing.map(w=>w.text).join(', ')+', or choose Mochi’s voice.');
if(mode==='standard'&&missing.length&&!voice)throw Error('The standard British voice is not available on this device. Choose Mochi’s voice or attach recordings.');
if(mode==='monster')await prepareWords(missing);
if(JSON.stringify(draft).length>3000000)throw Error('These files need too much space. Use smaller pictures or shorter recordings.');const changed=menuChanged(draft,count);state.config={words:JSON.parse(JSON.stringify(draft)),count,voiceMode:mode};syncRecordings();if(!Object.hasOwn(state.players,name))state.players[name]=newProgress();state.player=name;if(progress().active&&(changed||progress().active.words.some(w=>!draft.some(d=>C.normalize(d.text)===C.normalize(w.text))))){progress().previousOrder=progress().active;progress().active=null;clearTimeout(bakeTimer);}practice=null;if(!save())throw Error('The menu could not be saved on this device. Your draft is still here.');clearDraft();$('setup').close();render();$('saveStatus').textContent='Saved '+draft.length+' words. '+(changed?'Your next cake uses this menu.':'Your menu is ready.');}catch(err){voiceFailure(err);}};
function sharedMenus(){try{const a=JSON.parse(localStorage.getItem('bakery-shared-menus')||'[]');return Array.isArray(a)?a.filter(x=>x&&/^[a-f0-9]{64}$/.test(x.id)&&typeof x.title==='string').slice(0,20):[];}catch(_){return [];}}
function renderSharedMenus(){const host=$('sharedMenus');host.replaceChildren();for(const m of sharedMenus()){const row=document.createElement('p'),a=document.createElement('a');a.href='https://arsdashok.github.io/games/monster-bakery/#menu='+m.id;a.target='_blank';a.rel='noopener';a.textContent=m.title+' ('+m.count+' words)';row.append(a);host.append(row);}}
$('shareMenu').onclick=async()=>{if(preparing||shareBusy)return;shareBusy=true;$('shareMenu').disabled=true;$('shareResult').hidden=true;try{syncDraft();showDraft();const token=$('voiceToken').value.trim();if(token.length<24)throw Error('Sign in with Google to share a student menu.');if(!Number.isInteger(Number($('roundSize').value))||Number($('roundSize').value)<1||Number($('roundSize').value)>12)throw Error('Choose between 1 and 12 words per cake.');await prepareWords(draft);$('setupForm').querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);const menu={version:1,title:$('menuTitle').value.trim()||'Spelling practice',count:Number($('roundSize').value),words:draft.map(({text,cue,art,image,audio})=>({text,cue,art,image,audio}))};const serial=JSON.stringify(menu);if(serial.length>3000000)throw Error('This menu is too large. Use fewer or smaller pictures.');if(!shareRequest||shareRequest.serial!==serial)shareRequest={serial,id:window.BakeryMenus.newId()};$('shareStatus').textContent='Preparing your student link…';const url=await window.BakeryMenus.share(menu,token,shareRequest.id);$('studentLink').value=url;$('shareResult').hidden=false;$('shareStatus').textContent='Ready. This link includes the words and recordings. The student needs no sign-in.';const lists=sharedMenus().filter(m=>m.id!==shareRequest.id);lists.unshift({id:shareRequest.id,title:menu.title,count:menu.words.length});try{localStorage.setItem('bakery-shared-menus',JSON.stringify(lists.slice(0,20)));}catch(_){}renderSharedMenus();}catch(e){$('shareStatus').textContent=e.message;voiceFailure(e);}finally{shareBusy=false;$('setupForm').querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=false);showDraft();}};
$('copyStudentLink').onclick=async()=>{try{await navigator.clipboard.writeText($('studentLink').value);$('shareStatus').textContent='Link copied. Send it to your student.';}catch(_){$('studentLink').focus();$('studentLink').select();$('shareStatus').textContent='Select and copy the link above.';}};
async function openStudentMenu(){if(!sharedRequested){render();return;}$('settingsButton').hidden=true;panel('<p class="eyebrow">YOUR SPELLING MENU</p><h2 class="ready-title">Opening your words…</h2>');try{const menu=await window.BakeryMenus.load(sharedId);if(!menu||!Array.isArray(menu.words)||!menu.words.length||menu.words.length>50||!menu.words.every(validWord)||!Number.isInteger(menu.count)||menu.count<1||menu.count>12)throw Error('This menu could not be opened. Ask your teacher to check it.');sharedTitle=String(menu.title||'Spelling practice').slice(0,80);state.config={words:menu.words,count:menu.count,voiceMode:'recordings'};render();}catch(e){panel('<p class="eyebrow">YOUR SPELLING MENU</p><h2 class="ready-title">Let’s try that link again.</h2><p class="feedback-copy">'+esc(e.message)+'</p><button class="primary wide" id="retryMenu">Try again</button>');$('retryMenu').onclick=openStudentMenu;}}
$('setup').addEventListener('cancel',e=>{if(preparing||shareBusy)e.preventDefault();else rememberDraft();});
$('resetProgress').onclick=()=>{if(!confirm('Reset '+state.player+'’s stars and current cake? This cannot be undone.'))return;progress().stars=0;progress().orders=0;progress().active=null;practice=null;clearTimeout(bakeTimer);save();$('setup').close();render();};
window.addEventListener?.('hashchange',()=>window.location.reload());
$('saveWarning').hidden=storageOK;openStudentMenu();
})();
