(()=>{'use strict';const E=ExplorerEngine,$=id=>document.getElementById(id);let config={min:1,max:20,choices:4,goal:8,mode:'listen'},voice=null,bag=[],current=null,found=0,records=[],wrong=0,helped=false,finished=false,listened=false,speechToken=0;
try{let saved=JSON.parse(localStorage.getItem('number-explorer-v2-settings'));if(E.validate(saved||{}))config=saved}catch{}
function loadVoice(){voice=('speechSynthesis'in window)?speechSynthesis.getVoices().find(v=>v.name==='Google UK English Female'):null;$('voiceStatus').textContent=voice?'Voice ready: Google UK English Female.':'Google UK English Female is unavailable here. Use Read & find or Teacher calls the number.';if(current&&!finished&&config.mode==='listen')updateAudio()}
if('speechSynthesis'in window){speechSynthesis.addEventListener('voiceschanged',loadVoice)}loadVoice();
function stopSpeech(){speechToken++;if('speechSynthesis'in window)speechSynthesis.cancel();$('listen').classList.remove('speaking')}
function show(screen){for(const id of ['home','play','done'])$(id).hidden=id!==screen;document.body.classList.toggle('playing',screen==='play');const heading=$(screen).querySelector('h1,h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}}
function preview(){$('preview').textContent=`${config.min}–${config.max} · ${config.goal} crystals · ${config.mode==='listen'?'Listen & find':config.mode==='read'?'Read & find':'Teacher calls'}`}
function fillSettings(){for(const [id,key] of [['min','min'],['max','max'],['choiceCount','choices'],['goal','goal'],['mode','mode']])$(id).value=config[key];$('configError').textContent='';loadVoice()}
$('settingsBtn').onclick=()=>{stopSpeech();fillSettings();$('settings').showModal()};$('closeSettings').onclick=()=>$('settings').close();document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{[$('min').value,$('max').value]=b.dataset.range.split(',')});
$('settingsForm').onsubmit=e=>{e.preventDefault();let next={min:Number($('min').value),max:Number($('max').value),choices:Number($('choiceCount').value),goal:Number($('goal').value),mode:$('mode').value};if(!E.validate(next)){$('configError').textContent='Choose a range from 1 to 100, with at least two numbers.';return}config=next;try{localStorage.setItem('number-explorer-v2-settings',JSON.stringify(config))}catch{}$('settings').close();stopSpeech();current=null;show('home');preview()};
function updateProgress(){$('progressText').textContent=`${found} of ${config.goal} crystals`;$('crystals').replaceChildren(...Array.from({length:config.goal},(_,i)=>{let s=document.createElement('span');s.textContent='◆';s.className=i<found?'found':'';s.setAttribute('aria-hidden','true');return s}));$('crystals').setAttribute('aria-label',`${found} of ${config.goal} crystals collected`)}
function start(){bag=E.shuffle(E.pool(config));found=0;records=[];current=null;finished=false;show('play');round()}
function round(){stopSpeech();let prior=current;if(!bag.length){bag=E.shuffle(E.pool(config));if(bag.at(-1)===prior&&bag.length>1)[bag[0],bag[bag.length-1]]=[bag.at(-1),bag[0]]}current=bag.pop();wrong=0;helped=false;finished=false;listened=config.mode!=='listen';$('next').hidden=true;$('word').hidden=config.mode!=='read';$('word').textContent=E.words(current);$('reveal').hidden=config.mode!=='listen';$('listen').hidden=config.mode!=='listen';$('audioNotice').hidden=true;$('taskMode').textContent=config.mode==='listen'?'LISTEN & FIND':config.mode==='read'?'READ & FIND':'LISTEN TO YOUR TEACHER';$('instruction').textContent=config.mode==='read'?'Find this number.':config.mode==='teacher'?'Which number did your teacher say?':'Which number did you hear?';$('feedback').textContent=config.mode==='listen'?'Tap Listen when you’re ready.':'Take your time.';$('choices').classList.toggle('six',config.choices===6);$('choices').replaceChildren(...E.options(current,config).map(n=>{let b=document.createElement('button');b.className='number';b.textContent=n;b.onclick=()=>answer(n,b);return b}));if(config.mode==='teacher'){$('reveal').hidden=false;$('reveal').textContent='Teacher: show / hide number'}else $('reveal').textContent='Show the word';if(config.mode==='listen')updateAudio();updateProgress()}
function updateAudio(){const noVoice=!voice;$('listen').disabled=noVoice;$('audioNotice').hidden=!noVoice;$('audioNotice').textContent='Voice unavailable in this browser. Ask your teacher to read the word, or choose Read & find in Teacher settings.';if(noVoice)$('feedback').textContent='Your teacher can help with the word.'}
$('listen').onclick=()=>{if(!voice||!current||finished)return;stopSpeech();let u=new SpeechSynthesisUtterance(E.words(current));u.voice=voice;u.lang='en-GB';u.rate=.9;const token=speechToken;u.onstart=()=>{if(token===speechToken)$('listen').classList.add('speaking')};u.onend=()=>{if(token!==speechToken)return;$('listen').classList.remove('speaking');listened=true;$('feedback').textContent='Find the number.'};u.onerror=e=>{if(token!==speechToken||['canceled','interrupted'].includes(e.error))return;$('listen').classList.remove('speaking');$('audioNotice').hidden=false;$('audioNotice').textContent='Audio could not play. Tap Show the word or ask your teacher.'};speechSynthesis.speak(u)};
$('reveal').onclick=()=>{if(config.mode==='teacher'){$('word').hidden=!$('word').hidden;if(!$('word').hidden)helped=true;return}$('word').hidden=false;helped=true;listened=true;$('reveal').hidden=true;$('feedback').textContent='Read it, then find the number.'};
function answer(n,b){if(finished)return;if(!listened){$('feedback').textContent='Listen first, or tap Show the word.';return}if(n!==current){wrong++;b.classList.add('wrong');b.disabled=true;$('feedback').textContent='Have another look. You can try again.';return}finished=true;stopSpeech();found++;records.push({number:current,wrong,helped,mode:config.mode});b.classList.add('correct');for(const el of $('choices').children)el.disabled=true;$('feedback').textContent=['Crystal found!','That’s the one!','A new discovery!'][found%3];$('listen').hidden=true;$('reveal').hidden=true;$('next').hidden=false;$('next').textContent=found===config.goal?'See your discoveries →':'Next discovery →';updateProgress()}
$('next').onclick=()=>{if(!finished)return;if(found>=config.goal)complete();else{round();const focusTarget=config.mode==='listen'&&voice?$('listen'):$('instruction');focusTarget.tabIndex=0;focusTarget.focus({preventScroll:true})}};
function complete(){stopSpeech();show('done');$('result').textContent=`${found} crystals collected. Pip is ready for the journey!`;let independent=records.filter(r=>!r.wrong&&!r.helped).length,practise=[...new Set(records.filter(r=>r.wrong||r.helped).map(r=>r.number))];$('reportBody').replaceChildren();for(const t of [`First-choice answers without the word hint: ${independent} of ${records.length}.`,practise.length?`Worth revisiting: ${practise.join(', ')}.`:'No retries or word hints this expedition.',config.mode==='listen'?'Listening mode. Word-hint answers count towards the journey, not independent listening.':config.mode==='read'?'Reading mode: this does not assess listening.':'Teacher-led mode. Performance depends on the prompts and support you gave.']){let p=document.createElement('p');p.textContent=t;$('reportBody').append(p)}$('report').open=false}
$('start').onclick=start;$('again').onclick=start;$('back').onclick=()=>{current=null;show('home')};$('homeBtn').onclick=()=>{stopSpeech();$('pause').showModal()};$('resume').onclick=()=>$('pause').close();$('restart').onclick=()=>{$('pause').close();stopSpeech();current=null;show('home')};preview();show('home');})();
